apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam-server-backend
spec:
  selector:
    matchLabels:
      app: cam-server
  template:
    metadata:
      labels:
        app: cam-server
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: cam-server-backend
        image: gabbersepp/cam-server-backend
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /app/data
            name: sambashare
            subPath: securitycam/data
          - mountPath: /app/config
            name: sambashare
            subPath: securitycam/config
          - mountPath: /app/state
            name: sambashare
            subPath: securitycam/state
      volumes:
        - name: sambashare
          flexVolume:
            driver: "fstab/cifs"
            fsType: "cifs"
            secretRef:
              name: "cifs-secret"
            options:
              networkPath: "//192.168.2.126/sambashare"
              mountOptions: "uid=1001" #vlcuser

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam-proxy
spec:
  selector:
    matchLabels:
      app: cam-proxy
  template:
    metadata:
      labels:
        app: cam-proxy
    spec:
      nodeSelector:
        name: biehler
      hostNetwork: true
      #dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: cam-proxy
        image: gabbersepp/cam-proxy
        ports:
        - containerPort: 30200
          hostPort: 30200
          hostIP: 192.168.2.126
        - containerPort: 30201
          hostPort: 30201
          hostIP: 192.168.2.126
        - containerPort: 30202
          hostPort: 30202
          hostIP: 192.168.2.126
        - containerPort: 30203
          hostPort: 30203
          hostIP: 192.168.2.126
        - containerPort: 30204
          hostPort: 30204
          hostIP: 192.168.2.126
        - containerPort: 30205
          hostPort: 30205
          hostIP: 192.168.2.126
        - containerPort: 30206
          hostPort: 30206
          hostIP: 192.168.2.126
        - containerPort: 30207
          hostPort: 30207
          hostIP: 192.168.2.126
        - containerPort: 30208
          hostPort: 30208
          hostIP: 192.168.2.126
        - containerPort: 30209
          hostPort: 30209
          hostIP: 192.168.2.126
        - containerPort: 30210
          hostPort: 30210
          hostIP: 192.168.2.126
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /app/data
            name: sambashare
            subPath: securitycam/data
          - mountPath: /app/config
            name: sambashare
            subPath: securitycam/config
          - mountPath: /app/state
            name: sambashare
            subPath: securitycam/state
      volumes:
      - name: sambashare
        flexVolume:
          driver: "fstab/cifs"
          fsType: "cifs"
          secretRef:
            name: "cifs-secret"
          options:
            networkPath: "//192.168.2.126/sambashare"
            mountOptions: "uid=1001"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam-client
spec:
  selector:
    matchLabels:
      app: cam-client
  template:
    metadata:
      labels:
        app: cam-client
    spec:
      containers:
      - name: cam-client-frontend
        image: gabbersepp/cam-client-frontend
        ports:
          - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /usr/share/nginx/html/config
            name: config
            subPath: securitycam/config
      - name: cam-client-backend
        image: gabbersepp/cam-client-backend
        ports:
          - containerPort: 8080
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /app/data
          name: backup
          subPath: SecurityCam
        - mountPath: /app/config/
          name: config
          subPath: securitycam/config
        - mountPath: /app/state
          name: config
          subPath: securitycam/state
      volumes:
        - name: backup
          flexVolume:
            driver: "fstab/cifs"
            fsType: "cifs"
            # secret only dummy - share is Public
            secretRef:
              name: "cifs-secret-private-cloud"
            options:
              networkPath: "//biehlercloud/Public"
              mountOptions: "uid=1001"
        - name: config
          flexVolume:
            driver: "fstab/cifs"
            fsType: "cifs"
            secretRef:
              name: "cifs-secret"
            options:
              networkPath: "//192.168.2.126/sambashare"
              mountOptions: "uid=1001"

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cam-server-backup-memory-cleanup
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: cam-server-backup-memory-cleanup
              image: gabbersepp/cam-server-memory-cleanup
              volumeMounts:
                - mountPath: /app/data
                  name: backup
                  subPath: SecurityCam
                - mountPath: /app/config/
                  name: config
                  subPath: securitycam/config
              imagePullPolicy: Always
              env:
              - name: MAX_SIZE_MB
                value: "20000"
              - name: ONE_TIME
                value: "true"
              - name: EXCLUDE0
                value: "thumbnail"
          volumes:
          - name: backup
            flexVolume:
              driver: "fstab/cifs"
              fsType: "cifs"
              # secret only dummy - share is Public
              secretRef:
                name: "cifs-secret-private-cloud"
              options:
                networkPath: "//biehlercloud/Public"
                mountOptions: ""
          - name: config
            flexVolume:
              driver: "fstab/cifs"
              fsType: "cifs"
              secretRef:
                name: "cifs-secret"
              options:
                networkPath: "//192.168.2.126/sambashare"
                mountOptions: ""

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cam-server-backup
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cam-server-backup
              image: gabbersepp/cam-server-backup
              volumeMounts:
                - mountPath: /app/data
                  name: sambashare
                  subPath: securitycam/data
                - mountPath: /app/config/
                  name: sambashare
                  subPath: securitycam/config
                - mountPath: /app/backup
                  name: backup
                  subPath: SecurityCam
              env:
              - name: EXCLUDE0
                value: log.txt
              imagePullPolicy: Always
          restartPolicy: OnFailure
          volumes:
          - name: sambashare
            flexVolume:
              driver: "fstab/cifs"
              fsType: "cifs"
              secretRef:
                name: "cifs-secret"
              options:
                networkPath: "//192.168.2.126/sambashare"
                mountOptions: ""
          - name: backup
            flexVolume:
              driver: "fstab/cifs"
              fsType: "cifs"
              # secret only dummy - share is Public
              secretRef:
                name: "cifs-secret-private-cloud"
              options:
                networkPath: "//biehlercloud/Public"
                mountOptions: ""

---

apiVersion: v1
kind: Service
metadata:
  name: cam-client
spec:
  selector:
    app: cam-client
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: api
  - port: 80
    targetPort: 80
    name: web

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cam-client
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite /api/(.+)$ /$1 break;  
    nginx.ingress.kubernetes.io/whitelist-source-range:  192.168.2.0/24
spec:
  rules:
  - host: cam.h5b.de
    http:
      paths:
      - path: /api/
        backend:
          serviceName: cam-client
          servicePort: api
      - path: /
        backend:
          serviceName: cam-client
          servicePort: web
