apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam-server-backend
spec:
  selector:
    matchLabels:
      app: cam-server
  template:
    metadata:
      labels:
        app: cam-server
    spec:
      containers:
      - name: cam-server-backend
        image: gabbersepp/cam-server-backend
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /app/data
            name: data
          - mountPath: /app/config
            name: backendconfig
      - name: cam-server-memory-cleanup
        image: gabbersepp/cam-server-memory-cleanup
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /app/data
            name: data
        env:
          - name: MAX_SIZE_MB
            value: "2000"
          - name: EXCLUDE0
            value: frontendconfig.json
          - name: EXCLUDE1
            value: backendconfig.json
      volumes:
        - name: data
          hostPath:
              path: /securitycam
        - name: backendconfig
          hostPath:
            path: /securitycam/backendconfig/

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam-client
spec:
  selector:
    matchLabels:
      app: cam-client
  template:
    metadata:
      labels:
        app: cam-client
    spec:
      containers:
      - name: cam-client-frontend
        image: gabbersepp/cam-client-frontend
        ports:
          - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /usr/share/nginx/html/config
            name: frontendconfig
      - name: cam-client-backend
        image: gabbersepp/cam-client-backend
        ports:
          - containerPort: 8080
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /app/data
          name: backup
        - mountPath: /app/config/
          name: backendconfig
      volumes:
        - name: backup
          hostPath:
              path: /mnt/biehlercloud/SecurityCam
        - name: frontendconfig
          hostPath:
            path: /securitycam/frontendconfig/
        - name: backendconfig
          hostPath:
            path: /securitycam/backendconfig/

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cam-server-backup-memory-cleanup
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: cam-server-backup-memory-cleanup
              image: gabbersepp/cam-server-memory-cleanup
              volumeMounts:
                - mountPath: /app/data
                  name: backup
              imagePullPolicy: Always
              env:
              - name: MAX_SIZE_MB
                value: "20000"
              - name: ONE_TIME
                value: "true"
              - name: EXCLUDE0
                value: "thumbnail"
          volumes:
          - name: backup
            hostPath:
                path: /mnt/biehlercloud/SecurityCam

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cam-server-backup
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cam-server-backup
              image: gabbersepp/cam-server-backup
              volumeMounts:
                - mountPath: /app/data
                  name: data
                - mountPath: /app/backup
                  name: backup
              imagePullPolicy: Always
              env:
              - name: EXCLUDE0
                value: frontendconfig
              - name: EXCLUDE1
                value: backendconfig
          restartPolicy: OnFailure
          volumes:
          - name: data
            hostPath:
                path: /securitycam
          - name: backup
            hostPath:
                path: /mnt/biehlercloud/SecurityCam

---

apiVersion: v1
kind: Service
metadata:
  name: cam-client
spec:
  selector:
    app: cam-client
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30009
    name: backend-port
  - port: 80
    targetPort: 80
    nodePort: 30010
    name: frontend-port