apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam-server-backend
spec:
  selector:
    matchLabels:
      app: cam-server
  template:
    metadata:
      labels:
        app: cam-server
    spec:
      containers:
      - name: cam-server-backend
        image: gabbersepp/cam-server-backend
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /app/data
            name: sambashare
            subPath: securitycam/data
          - mountPath: /app/config
            name: sambashare
            subPath: securitycam/config
      - name: cam-server-memory-cleanup
        image: gabbersepp/cam-server-memory-cleanup
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /app/data
            name: sambashare
            subPath: securitycam/data
          - mountPath: /app/config
            name: sambashare
            subPath: securitycam/config
        env:
          - name: MAX_SIZE_MB
            value: "2000"
          - name: EXCLUDE0
            value: frontendconfig.json
          - name: EXCLUDE1
            value: backendconfig.json
      volumes:
        - name: sambashare
          flexVolume:
            driver: "fstab/cifs"
            fsType: "cifs"
            secretRef:
              name: "cifs-secret"
            options:
              networkPath: "//192.168.2.126/sambashare"
              mountOptions: "uid=1001" #vlcuser

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam-client
spec:
  selector:
    matchLabels:
      app: cam-client
  template:
    metadata:
      labels:
        app: cam-client
    spec:
      containers:
      - name: cam-client-frontend
        image: gabbersepp/cam-client-frontend
        ports:
          - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /usr/share/nginx/html/config
            name: config
            subPath: securitycam/config
      - name: cam-client-backend
        image: gabbersepp/cam-client-backend
        ports:
          - containerPort: 8080
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /app/data
          name: backup
          subPath: SecurityCam
        - mountPath: /app/config/
          name: config
          subPath: securitycam/config
      volumes:
        - name: backup
          flexVolume:
            driver: "fstab/cifs"
            fsType: "cifs"
            # secret only dummy - share is Public
            secretRef:
              name: "cifs-secret-private-cloud"
            options:
              networkPath: "//biehlercloud/Public"
              mountOptions: "uid=1001"
        - name: config
          flexVolume:
            driver: "fstab/cifs"
            fsType: "cifs"
            secretRef:
              name: "cifs-secret"
            options:
              networkPath: "//192.168.2.126/sambashare"
              mountOptions: "uid=1001"

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cam-server-backup-memory-cleanup
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: cam-server-backup-memory-cleanup
              image: gabbersepp/cam-server-memory-cleanup
              volumeMounts:
                - mountPath: /app/data
                  name: backup
                  subPath: SecurityCam
                - mountPath: /app/config/
                  name: config
                  subPath: securitycam/config
              imagePullPolicy: Always
              env:
              - name: MAX_SIZE_MB
                value: "20000"
              - name: ONE_TIME
                value: "true"
              - name: EXCLUDE0
                value: "thumbnail"
          volumes:
          - name: backup
            flexVolume:
              driver: "fstab/cifs"
              fsType: "cifs"
              # secret only dummy - share is Public
              secretRef:
                name: "cifs-secret-private-cloud"
              options:
                networkPath: "//biehlercloud/Public"
                mountOptions: ""
          - name: config
            flexVolume:
              driver: "fstab/cifs"
              fsType: "cifs"
              secretRef:
                name: "cifs-secret"
              options:
                networkPath: "//192.168.2.126/sambashare"
                mountOptions: ""

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cam-server-backup
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cam-server-backup
              image: gabbersepp/cam-server-backup
              volumeMounts:
                - mountPath: /app/data
                  name: sambashare
                  subPath: securitycam/data
                - mountPath: /app/config/
                  name: sambashare
                  subPath: securitycam/config
                - mountPath: /app/backup
                  name: backup
                  subPath: SecurityCam
              imagePullPolicy: Always
          restartPolicy: OnFailure
          volumes:
          - name: sambashare
            flexVolume:
              driver: "fstab/cifs"
              fsType: "cifs"
              secretRef:
                name: "cifs-secret"
              options:
                networkPath: "//192.168.2.126/sambashare"
                mountOptions: ""
          - name: backup
            flexVolume:
              driver: "fstab/cifs"
              fsType: "cifs"
              # secret only dummy - share is Public
              secretRef:
                name: "cifs-secret-private-cloud"
              options:
                networkPath: "//biehlercloud/Public"
                mountOptions: ""

---

apiVersion: v1
kind: Service
metadata:
  name: cam-client
spec:
  selector:
    app: cam-client
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30009
    name: backend-port
  - port: 80
    targetPort: 80
    nodePort: 30010
    name: frontend-port